# -*- coding: utf-8 -*-

COMMENT_TAG_DEFAULT = 'AUTO_EOM'
COMMENT_SUFFIX = ':SOCKET_KITCHEN_UNIT'

DEFAULT_HEIGHT_MM = 1100
TOTAL_TARGET = 4

CLEAR_SINK_MM = 600
CLEAR_STOVE_MM = 600

OFFSET_SINK_MM = 600
OFFSET_STOVE_MM = 600

WALL_END_CLEAR_MM = 100
FIXTURE_WALL_MAX_DIST_MM = 2000

DEDUPE_MM = 300
BATCH_SIZE = 25

# Validation tolerances
VALIDATE_MATCH_TOL_MM = 2000
VALIDATE_HEIGHT_TOL_MM = 20
VALIDATE_WALL_DIST_MM = 150
VALIDATE_OFFSET_TOL_MM = 100

DEBUG_NO_CANDIDATES_LIMIT = 3
DEBUG_SKIPPED_ROOMS_LIMIT = 20
EXISTING_DEDUPE_MM = 200

DEFAULT_KITCHEN_PATTERNS = [u'кухн', u'kitchen', u'столов']

DEFAULT_FAMILY_NAMES = [
    u'TSL_EF_т_СТ_в_IP20_Рзт_1P+N+PE_2п : TSL_EF_т_СТ_в_IP20_Рзт_1P+N+PE_2п',
]
