# -*- coding: utf-8 -*-

COMMENT_TAG_DEFAULT = 'AUTO_EOM'
COMMENT_INTERCOM = ':SOCKET_INTERCOM'
COMMENT_ROUTER = ':SOCKET_ROUTER'

BATCH_SIZE = 25

DEFAULT_INTERCOM_HEIGHT_MM = 1400
DEFAULT_ROUTER_HEIGHT_MM = 300
DEFAULT_SEARCH_RADIUS_MM = 1500
DEFAULT_DOOR_OFFSET_MM = 300
DEFAULT_DOOR_PROBE_MM = 400
DEFAULT_MAX_WALL_DIST_MM = 2500
DEFAULT_DEDUPE_MM = 300
DEFAULT_INTERCOM_OFFSET_MM = 200
DEFAULT_ROUTER_OFFSET_MM = 200

INTERCOM_KEYWORDS = [u'домоф', u'intercom', u'видеодо', u'вызывн', u'панел']
CABINET_KEYWORDS = [u'сск', u'слаботоч', u'щит сс', u'шкаф сс', u'роутер', u'router', u'коробк', u'распа']
