# -*- coding: utf-8 -*-


def get_avcounts_globals(doc=None, uidoc=None, icon=None):
    data = {
        "doc": doc,
        "uidoc": uidoc,
        "avt_family_names": [
            u"TSL_2D автоматический выключатель_ВРУ",
            u"TSL_2D автоматический выключатель_Щит",
        ],
        "calculated_tables_family_names": [
            u"TSL_Таблица_Расчетная для схемы",
            u"TSL_Таблица_Расчетная для щитов",
        ],
        "Note_table_family_name": [
            u"TSL_Понижающие коэффициенты",
        ],
        "using_any_avtomats": [
            u"TSL_Вводной автомат для щитов",
            u"TSL_Любой автомат для схем",
        ],
        "using_reserve_avtomats": [
            u"TSL_Резервный автомат для ВРУ",
            u"TSL_Резервный автомат для щитов",
        ],
        "using_auxiliary_cables": [
            u"TSL_Кабель",
            u"TSL_Кабель с текстом 1.8",
        ],
        "fam_param_names": [
            u"ADSK_Единица измерения",
            u"ADSK_Завод-изготовитель",
            u"ADSK_Наименование",
            u"ADSK_Обозначение",
            u"ADSK_Код изделия",
            u"ADSK_Примечание",
        ],
        "Param_Py": "Py",
        "Param_Kc": "Kc",
        "Param_Pp": "Pp",
        "Param_Cosf": "Cosf",
        "Param_Ip": "Ip",
        "Param_Sp": "Sp",
        "Param_Upit": u"Напряжение",
        "Param_Cable_length": u"Длина проводника",
        "Param_Accessory": u"Принадлежность щиту",
        "Param_Circuit_number": u"Номер цепи",
        "Param_Cable_section": u"Сечение проводника",
        "Param_Circuit_breaker_nominal": u"Уставка аппарата",
        "Param_Voltage_drop": u"Потери",
        "Param_Moment": u"Момент",
        "Param_Wire_brand": u"Марка проводника",
        "Param_PE_section": u"Сечение проводника PE",
        "Param_3phase_CB": u"3-фазный аппарат",
        "Param_Flat_type_1": u"Кол-во квартир 1 типа",
        "Param_Flat_type_2": u"Кол-во квартир 2 типа",
        "Param_Flat_type_3": u"Кол-во квартир 3 типа",
        "Param_Flat_type_4": u"Кол-во квартир 4 типа",
        "Param_Flat_type_5": u"Кол-во квартир 5 типа",
        "Param_Flat_type_6": u"Кол-во квартир 6 типа",
        "Param_PpPv_Flat_type_1": u"Рр или Рвыд одной квартиры 1 типа (кВт)",
        "Param_PpPv_Flat_type_2": u"Рр или Рвыд одной квартиры 2 типа (кВт)",
        "Param_PpPv_Flat_type_3": u"Рр или Рвыд одной квартиры 3 типа (кВт)",
        "Param_PpPv_Flat_type_4": u"Рр или Рвыд одной квартиры 4 типа (кВт)",
        "Param_PpPv_Flat_type_5": u"Рр или Рвыд одной квартиры 5 типа (кВт)",
        "Param_PpPv_Flat_type_6": u"Рр или Рвыд одной квартиры 6 типа (кВт)",
        "Param_Laying_Method": u"Способ прокладки",
        "Param_Internal_pipe_diameter": u"Условный проход",
        "Param_Wires_quantity": u"Количество жил",
        "Param_Module_quantity": u"Кол-во модулей",
        "Param_Pole_quantity": u"Кол-во полюсов",
        "Param_Visibility_Knife_switch": u"Рубильник",
        "Param_Visibility_Circuit_breaker": u"Автоматический выключатель",
        "Param_Visibility_RCCB": u"Дифф.автомат",
        "Param_Visibility_RCD": u"УЗО",
        "Param_Current_breaker_overestimated": u"Номинал защиты больше Ip",
        "Param_Cab_section_overestimated": u"Сечение больше необходимого",
        "Param_Electric_receiver_Name": u"Наименование электроприёмника",
        "Param_Rays_quantity": u"Количество лучей",
        "Param_Conductor_quantity": u"Количество проводников",
        "Param_PE_Conductor_quantity": u"Количество проводников PE",
        "Param_Load_Class": u"Классификация нагрузок",
        "Param_Explanation": u"Пояснение",
        "Param_Breaking_capacity": u"Отключающая способность (кА)",
        "Param_CB_type": u"Тип аппарата",
        "Param_CB_characteristic": u"Характеристика аппарата",
        "Param_Leakage_current": u"Ток утечки УЗО",
        "Param_Consumers_count": u"Число электроприёмников",
        "Param_SchSize_Height": u"Высота (мм)",
        "Param_SchSize_Width": u"Ширина (мм)",
        "Param_SchSize_Depth": u"Глубина (мм)",
        "Param_ADSK_product_code": u"ADSK_Код изделия",
        "Param_SpecifyByName": u"Выписывать по наименованию",
        "Param_TypeLeakage_current": u"Тип тока утечки",
        "Param_Short_Circuit_3ph": u"Ток КЗ 3ф (кА)",
        "Param_Short_Circuit_1ph": u"Ток КЗ 1ф (кА)",
        "Param_IdQFsCalc": u"Id расчётных аппаратов",
        "Param_ReducedWireLength": u"Длина проводника приведённая",
        "Guidstr_Param_Names_Storage": "44bf8d44-4a4a-4fde-ada8-cd7d802648c4",
        "SchemaName_for_Param_Names_Storage": "Param_Names_Storage",
        "FieldName_for_Param_Names_Storage": "Param_Names_Storage_list",
        "Guidstr": "c94ca2e5-771e-407d-9c09-f62feb4448b6",
        "FieldName_for_Tesla_settings": "Tesla_settings_list",
        "Cable_section_calculation_method_for_Tesla_settings": "Cable_section_calculation_method",
        "Volt_Dropage_key_for_Tesla_settings": "Volt_Dropage_key",
        "DeltaU_boundary_value_for_Tesla_settings": "deltaU_boundary_value",
        "Round_value_for_Tesla_settings": "Round_value_ts",
        "Require_tables_select_for_Tesla_settings": "Require_tables_select_ts",
        "Select_Cable_by_DeltaU_for_Tesla_settings": "Select_Cable_by_DeltaU_ts",
        "flat_calculation_way_for_Tesla_settings": "flat_calculation_way_ts",
        "Distributed_Volt_Dropage_koefficient_for_Tesla_settings": "Distributed_Volt_Dropage_koefficient",
        "Guidstr_Distributed_volt_dropage_Tesla_settings": "64261417-f3b0-4156-9db2-5c2fd1fd2059",
        "SchemaName_for_Distributed_volt_dropage_Tesla_settings": "Distributed_volt_dropage_Tesla_settings_Storage",
        "FieldName_for_Distributed_volt_dropage_Tesla_settings": "Distributed_volt_dropage_Tesla_settings_list",
        "Guidstr_CR": "c96a640d-7cf1-47dd-bd1d-1a938122227f",
        "SchemaName_for_CR": "Tesla_CR_Storage",
        "FieldName_for_CR_1": "Sections_of_cables_CR",
        "FieldName_for_CR_2": "Currents_for_multiwire_copper_cables_CR",
        "FieldName_for_CR_3": "Currents_for_multiwire_aluminium_cables_CR",
        "FieldName_for_CR_4": "Currents_for_singlewire_copper_cables_CR",
        "FieldName_for_CR_5": "Currents_for_singlewire_aluminium_cables_CR",
        "FieldName_for_CR_6": "Current_breaker_nominal_CR",
        "FieldName_for_CR_7": "Cables_trays_reduction_factor_CR",
        "FieldName_for_CR_8": "Circuit_breakers_reduction_factor_CR",
        "FieldName_for_CR_9": "Volt_dropage_coeffitients_CR",
        "FieldName_for_CR_10": "Currents_for_1phase_multiwire_copper_cables_DB",
        "FieldName_for_CR_11": "Currents_for_1phase_multiwire_aluminium_cables_DB",
        "FieldName_for_CR_12": "Voltage_CR",
        "Guidstr_Kc_Storage": "3de55145-e17d-4f10-be27-daf375c317af",
        "SchemaName_for_Kc": "Koefficients_Storage",
        "FieldName_for_Kc_1": "Kkr_flats_koefficient",
        "FieldName_for_Kc_2": "Flat_count_SP",
        "FieldName_for_Kc_3": "Flat_unit_wattage_SP",
        "FieldName_for_Kc_4": "Py_high_comfort",
        "FieldName_for_Kc_5": "Ks_high_comfort",
        "FieldName_for_Kc_6": "Flat_count_high_comfort",
        "FieldName_for_Kc_7": "Ko_high_comfort",
        "FieldName_for_Kc_8": "Kcpwrres",
        "FieldName_for_Kc_9": "Elevator_count_SP",
        "FieldName_for_Kc_10": "Ks_elevators_below12",
        "FieldName_for_Kc_11": "Ks_elevators_above12",
        "FieldName_for_Kc_12": "Load_Class_elevators",
        "FieldName_for_Kc_13": "Load_Class_falts",
        "FieldName_for_Kc_14": "Ks_Reserve_1",
        "FieldName_for_Kc_15": "Ks_Reserve_2",
        "Guidstr_AV_ListDB_ManufacturerSelect": "b9081bd1-6c79-478d-8ac0-9af54da5b8a0",
        "SchemaName_for_AV_ListDB_ManufacturerSelect": "AV_ListDB_ManufacturerSelect_Storage",
        "FieldName_for_AV_ListDB_ManufacturerSelect": "AV_ListDB_ManufacturerSelect_list",
        "Guidstr_ManufNames_ManufacturerSelect": "d17eba7e-01db-4c04-ad54-3a73437731d1",
        "SchemaName_for_ManufNames_ManufacturerSelect": "ManufNames_ManufacturerSelect_Storage",
        "FieldName_for_ManufNames_ManufacturerSelect": "ManufNames_ManufacturerSelect_list",
        "Guidstr_UserKc": "3772f576-269f-4c05-8fa9-c5f9e5f65390",
        "SchemaName_for_UserKc": "UserKc_SchemaName",
        "FieldName_for_UserKc": "UserKc_FieldName",
        "Guidstr_UserP": "c1a6b65b-822c-4091-8592-b8252b3bdbc4",
        "SchemaName_for_UserP": "UserP_SchemaName",
        "FieldName_for_UserP": "UserP_FieldName",
        "Guidstr_UserFormula": "d87d5871-ed16-4003-9a23-6c9fc3860600",
        "SchemaName_for_UserFormula": "UserFormula_SchemaName",
        "FieldName_for_UserFormula": "UserFormula_FieldName",
        "Guidstr_ManufacturerSettings": "8a3c4aad-74f6-46b2-b685-d17cd7c53a6b",
        "SchemaName_for_ManufacturerSettings": "ManufacturerSettings_SchemaName",
        "FieldName_for_ManufacturerSettings": "ManufacturerSettings_FieldName",
        "Guidstr_ManufNames_ManufacturerSelectCable": "fc725aed-20ed-4d44-984c-522c476e3abc",
        "SchemaName_for_ManufNames_ManufacturerSelectCable": "ManufNames_ManufacturerSelect_StorageCable",
        "FieldName_for_ManufNames_ManufacturerSelectCable": "ManufNames_ManufacturerSelect_listCable",
        "Guidstr_Cable_ListDB_ManufacturerSelect": "895e7aef-18fd-4e6c-b8f2-73af53f04aba",
        "SchemaName_for_Cable_ListDB_ManufacturerSelect": "Cable_ListDB_ManufacturerSelect_Storage",
        "FieldName_for_Cable_ListDB_ManufacturerSelect": "Cable_ListDB_ManufacturerSelect_list",
    }
    if icon is not None:
        data["iconmy"] = icon
    return data
