# -*- coding: utf-8 -*-


def get_shortcircuit_globals(doc=None, uidoc=None, icon=None):
    data = {
        "doc": doc,
        "uidoc": uidoc,
        "Guidstr_ShortCircuit_Settings": "feed43d6-2017-4488-a83f-8fde400df18e",
        "SchemaName_for_ShortCircuit_Settings": "ShortCircuit_Settings_Storage",
        "FieldName_for_ShortCircuit_Settings_1": "Transformer_Power_DB",
        "FieldName_for_ShortCircuit_Settings_2": "Resistance_r1t_Transformer_forward_reverse_DB",
        "FieldName_for_ShortCircuit_Settings_3": "Resistance_x1t_Transformer_forward_reverse_DB",
        "FieldName_for_ShortCircuit_Settings_4": "Resistance_z1t_Transformer_forward_reverse_DB",
        "FieldName_for_ShortCircuit_Settings_5": "Resistance_r1_1t_Transformer_1phSC_DB",
        "FieldName_for_ShortCircuit_Settings_6": "Resistance_x1_1t_Transformer_1phSC_DB",
        "FieldName_for_ShortCircuit_Settings_7": "Resistance_z1_1t_Transformer_1phSC_DB",
        "FieldName_for_ShortCircuit_Settings_8": "QF_Rated_current",
        "FieldName_for_ShortCircuit_Settings_9": "QF_Resistance_rkv",
        "FieldName_for_ShortCircuit_Settings_10": "QF_Resistance_xkv",
        "Guidstr_ShortCircuit_Main": "413cb225-2262-46a9-a9b5-61a2579540eb",
        "SchemaName_for_ShortCircuit_Main": "ShortCircuit_Main_Storage",
        "FieldName_for_ShortCircuit_Main_1": "ChainSectionsInfo_DB",
        "FieldName_for_ShortCircuit_Main_2": "DifSettings_Info_DB",
        "FieldName_for_ShortCircuit_Main_3": "QFsCount_Info_DB",
        "Guidstr_CR": "c96a640d-7cf1-47dd-bd1d-1a938122227f",
        "SchemaName_for_CR": "Tesla_CR_Storage",
        "FieldName_for_CR_1": "Sections_of_cables_CR",
        "FieldName_for_CR_2": "Currents_for_multiwire_copper_cables_CR",
        "FieldName_for_CR_3": "Currents_for_multiwire_aluminium_cables_CR",
        "FieldName_for_CR_4": "Currents_for_singlewire_copper_cables_CR",
        "FieldName_for_CR_5": "Currents_for_singlewire_aluminium_cables_CR",
        "FieldName_for_CR_6": "Current_breaker_nominal_CR",
        "FieldName_for_CR_7": "Cables_trays_reduction_factor_CR",
        "FieldName_for_CR_8": "Circuit_breakers_reduction_factor_CR",
        "FieldName_for_CR_9": "Volt_dropage_coeffitients_CR",
        "FieldName_for_CR_10": "Currents_for_1phase_multiwire_copper_cables_DB",
        "FieldName_for_CR_11": "Currents_for_1phase_multiwire_aluminium_cables_DB",
        "FieldName_for_CR_12": "Voltage_CR",
        "FieldName_for_CR_13": "Resistance_Active_Specific_for_copper_cables_DB",
        "FieldName_for_CR_14": "Resistance_Active_Specific_for_aluminium_cables_DB",
        "FieldName_for_CR_15": "Resistance_Inductive_Specific_for_all_cables_DB",
        "avt_family_names": [
            u"TSL_2D автоматический выключатель_ВРУ",
            u"TSL_2D автоматический выключатель_Щит",
        ],
        "using_auxiliary_cables": [
            u"TSL_Кабель",
            u"TSL_Кабель с текстом 1.8",
        ],
        "using_any_avtomats": [
            u"TSL_Вводной автомат для щитов",
            u"TSL_Любой автомат для схем",
        ],
        "using_reserve_avtomats": [
            u"TSL_Резервный автомат для ВРУ",
            u"TSL_Резервный автомат для щитов",
        ],
        "Param_Upit": u"Напряжение",
        "Param_Cable_length": u"Длина проводника",
        "Param_Cable_section": u"Сечение проводника",
        "Param_Circuit_breaker_nominal": u"Уставка аппарата",
        "Param_Wire_brand": u"Марка проводника",
        "Param_Rays_quantity": u"Количество лучей",
        "Param_Breaking_capacity": u"Отключающая способность (кА)",
        "Param_Circuit_number": u"Номер цепи",
        "Param_Short_Circuit_3ph": u"Ток КЗ 3ф (кА)",
        "Param_Short_Circuit_1ph": u"Ток КЗ 1ф (кА)",
        "Guidstr_ManufNames_ManufacturerSelectCable": "fc725aed-20ed-4d44-984c-522c476e3abc",
        "SchemaName_for_ManufNames_ManufacturerSelectCable": "ManufNames_ManufacturerSelect_StorageCable",
        "FieldName_for_ManufNames_ManufacturerSelectCable": "ManufNames_ManufacturerSelect_listCable",
        "Guidstr_Cable_ListDB_ManufacturerSelect": "895e7aef-18fd-4e6c-b8f2-73af53f04aba",
        "SchemaName_for_Cable_ListDB_ManufacturerSelect": "Cable_ListDB_ManufacturerSelect_Storage",
        "FieldName_for_Cable_ListDB_ManufacturerSelect": "Cable_ListDB_ManufacturerSelect_list",
    }
    if icon is not None:
        data["iconmy"] = icon
    return data
